# Generated by Django 5.0 on 2024-01-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='projetc',
            new_name='project',
        ),
    ]
